export const baseurl = "https://tastezeal.in/testlogin/"
export const login = "login.php"
export const signup = "register.php"
export const addkhata = "addkhata.php"
export const dashboard = "dashboard.php"