//export const baseurl = "https://tastezeal.in/testlogin/"
export const baseurl = "https://api.tastezeal.in/"
export const login = "login"
export const signup = "register"
export const addkhata = "addkhata"
export const dashboard = "dashboard"
export const editkhata = "editkhata"